### ISSUE TITLE
M18: Ereignis/Gemeinschaftsfeld

### ISSUE THREAD

**Issue by desertfox94** [desertfox94/fhl.swt.monopoly#11]
**Kurzbeschreibung**
Spieler zieht eine Ereignis- oder Gemeinschaftskarte.

**Vorbedingung**
- Spieler hat seine Figur bewegt.
- Die neue Position ist ein Ereignis- oder Gemeinschaftsfeld. 

**Normalverlauf**
1. Spieler zieht eine Ereignis- oder Gemeinschaftskarte.
2. Effekt der Karte wird ausgelöst.

**Nachbedingung**
Karte wird unten in den Stapel gelegt.

**Priorität:**
2

**Story Points**
5

**Comment by krachbumm3nte** [comment]
Dazu gehören erste frameworks für häufig in ähnlicher form auftretende karten (z.B.: zahle/ziehe ein xxxDM)
