### ISSUE TITLE
M31: Durch Pasch würfeln freikommen

### ISSUE THREAD

**Issue by desertfox94** [desertfox94/fhl.swt.monopoly#15]
**Kurzbeschreibung**
Ein Spieler im Gefängnis würfelt drei Mal, und hofft auf einen Pasch .

**Vorbedingung**
Spieler ist im Gefängnis.

**Normalverlauf**
- Spieler würfelt
- Pasch? -> er kommt frei
- kein Pasch und weniger als 3 Mal gewürfelt ? -> nochmal würfeln
- kein Pasch und 3 Mal gewürfelt? -> Spieler bleibt im Gefängnis 
 
**Alternativverlauf**
Auch ohne Pasch kommt ein Spieler frei, wenn es seine dritte Runde im Gefängnis war.

**Priorität:**
2

**Story Points**
2

**Comment by Cpt-J** [comment]
wenn pro runde nur 1x gewürfelt werden darf, dann halte ich dies für in Ordnung
