### ISSUE TITLE
M11: Auf Straße kommen

### ISSUE THREAD

**Issue by desertfox94** [desertfox94/fhl.swt.monopoly#28]
**Kurzbeschreibung**
Der Spieler kommt auf eine Straße.

**Vorbedingung**
- Spieler ist in diesem Zug auf einer Straße gelandet

**Normalverlauf**
Spieler kommt auf eine Straße und kann entscheiden ob er die Straße
- kaufen möchte (M12)
- zur Auktion freigeben möchte (M13)

**Alternativverlauf**
Wenn die Straße im Besitz eines anderen ist Miete bezahlen

**Priorität:**
1

**Story Points**
5

**Comment by krachbumm3nte** [comment]
häuser/hotels bauen ist laut der regeln nicht von der Spielerposition abhänging, sondern kann bei jedem Spielzug durchgeführt werden. wurde aus dem anwendungsfall gelöscht.

**Comment by Cpt-J** [comment]
nicht mvc pattern

**Comment by Cpt-J** [comment]
Ich weiß  nicht was da zu ändern ist
