### ISSUE TITLE
M19: Miete Bezahlen

### ISSUE THREAD

**Issue by desertfox94** [desertfox94/fhl.swt.monopoly#29]
**Kurzbeschreibung**
Ein Spieler kommt auf eine Straße und muss für diese Miete bezahlen.

**Vorbedingung**
 - Straße ist im Besitz eines anderen Spielers.
 - Straße ist nicht mit einer Hypothek belastet.
 - Besitzer der Straße ist nicht im Gefängnis.
 - Spieler ist nicht Bankrott.

**Normalverlauf**
1. Spieler erreicht die Straße.
 2. Spieler bezahlt die Miete. 

**Alternativverlauf**
 Spieler hat nicht ausreichend finanzielle Mittel:
 a.) Spieler nimmt Hypothek(en) auf und wird so liquide.
b.) Spieler hat nicht kann nicht genug finanzielle Mittel aufbringen und geht Bankrott.

**Nachbedingung**
Wenn ein Spieler Bankrott geht muss das Spiel beendet werden

**Priorität:**
1

**Story Points**
5

**Comment by Cpt-J** [comment]
Die Abfrage ob der Besitzer im Gefängnis ist, ist noch immer nach der abfrage ob der Spieler denn genug Geld hat.

Was ist wenn der Spieler zu wenig Geld hat, aber keine Strasse oder Häuser besitzt?
