### ISSUE TITLE
Git-repository aufräumen

### ISSUE THREAD

**Issue by krachbumm3nte** [desertfox94/fhl.swt.monopoly#46]
Das repository, sowie die gitigore müssen überarbeitet werden, sodass keine lokalen informationen ins repository kommen.

encoding probleme

einige Dateien sind in UTF-8, während andere in cp1252 formatiert sind. dies problem soll entweder im git oder in der ide gelöst werden.

**Comment by maelcum01** [comment]
.gitconfig und .gitattributes und der "cp1252"-diff wurden erzeugt.
