### ISSUE TITLE
M14: Hypothek aufnehmen

### ISSUE THREAD

**Issue by desertfox94** [desertfox94/fhl.swt.monopoly#8]
**Kurzbeschreibung**
Spieler nimmt eine Hypothek für eine seiner Straßen auf.

**Vorbedingung**
- Spieler ist am Zug 
- Spieler ist frei
- Spieler hat (min.) eine Straße ohne Hypothek

**Normalverlauf**
1. Spieler wählt eine Straße aus auf die er eine Hypothek aufnehmen will.
2. Straße wird mit Hypothek belastet.
3. Spieler bekommt Geld gutgeschrieben.

**Nachbedingung**
- Straße verursacht keine Mietkosten mehr.
- Straße kann nicht bebaut werden.

**Priorität:**
2

**Story Points**
8

**Comment by Lunchy** [comment]
Es wird dem Spieler kein Geld gutgeschrieben

**Comment by Cpt-J** [comment]
Ich habe einen Fehler im commit gemacht. Bitte auch bei  M15 schauen
