### ISSUE TITLE
M15: Hypothek abbezahlen

### ISSUE THREAD

**Issue by desertfox94** [desertfox94/fhl.swt.monopoly#9]
**Kurzbeschreibung**
Spieler zahlt eine Hypothek für eine Straße ab.

**Vorbedingung**
- Spieler ist am Zug 
- Spieler ist frei
- Spieler hat (min.) eine Straße mit Hypothek.

**Normalverlauf**
1. Spieler wählt eine Straße aus für die er die Hypothek abbezahlen will.
2. Spieler bezahlt Geld.
3. Straße wird von Hypothek befreit.

**Alternativverlauf**
Wenn der Spieler nicht genug Geld besitzt, kann er die Hypothek nicht abbezahlen.

**Nachbedingung**
Straße ist nicht mehr mit Hypothek belastet.

**Priorität:**
2

**Story Points**
3

**Comment by krachbumm3nte** [comment]
reopened: test läuft nicht durch

**Comment by Lunchy** [comment]
Review: Liegt an Hypotek aufnhemen nicht abbezahlen... Da dies eine vorraus bedinigung für abbezahlen ist.
